build: false

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
    - PYTHON_VERSION: 3.4
      MINICONDA: C:\Miniconda3

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy scikit-image nose"
  - activate test-environment
  - pip install coverage rednose mock
  - "python appveyor\\install.py"
  - "dir C:\\bftools"
  - "dir C:\\FreeImage\\Dist\\x32"
  - "set PATH=C:\\bftools;%PATH%"
  - "set PATH=C:\\FreeImage\\Dist\\x32;%PATH%"
  - "ECHO %PATH%"
  - python setup.py install


test_script:
  - nosetests
